# Generated by Django 5.2 on 2025-07-29 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nem_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelDataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='fuel_data_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
