# Generated by Django 5.2 on 2026-08-06 00:03

import django.core.validators
import django.db.models.deletion
import nem_price_lab.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceDataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='nem_price_uploads/', validators=[django.core.validators.FileExtensionValidator(['csv']), nem_price_lab.models.validate_csv_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.TextField(blank=True, default='', help_text='Import summary (filled automatically).')),
            ],
            options={
                'verbose_name': 'Price data upload',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ForecastRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('NSW1', 'NSW1'), ('QLD1', 'QLD1'), ('VIC1', 'VIC1'), ('SA1', 'SA1'), ('TAS1', 'TAS1')], max_length=8)),
                ('model_key', models.CharField(max_length=40)),
                ('issued_at', models.DateTimeField(help_text='Forecast origin. Nothing after this instant may inform the run.')),
                ('horizon_days', models.PositiveSmallIntegerField(default=7)),
                ('temperature_source', models.CharField(choices=[('forecast', 'Forecast temperature (leakage-safe)'), ('observed-fallback', 'Observed temperature (backfilled: optimistic)'), ('none', 'No temperature used')], default='none', max_length=20)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Fitted coefficients, for display and audit.')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-issued_at', 'region', 'model_key'],
                'indexes': [models.Index(fields=['region', 'issued_at'], name='nem_price_l_region_2865ac_idx')],
                'constraints': [models.UniqueConstraint(fields=('region', 'model_key', 'issued_at'), name='uniq_region_model_issued')],
            },
        ),
        migrations.CreateModel(
            name='RegionPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('NSW1', 'NSW1'), ('QLD1', 'QLD1'), ('VIC1', 'VIC1'), ('SA1', 'SA1'), ('TAS1', 'TAS1')], max_length=8)),
                ('interval_end', models.DateTimeField(help_text='End of the 30-minute interval, NEM time (UTC+10).')),
                ('rrp', models.FloatField(help_text='Regional reference price, $/MWh, mean of the 5-minute prices.')),
                ('total_demand', models.FloatField(help_text='Total demand, MW, mean across the interval.')),
            ],
            options={
                'ordering': ['region', 'interval_end'],
                'indexes': [models.Index(fields=['region', 'interval_end'], name='nem_price_l_region_93a496_idx')],
                'constraints': [models.UniqueConstraint(fields=('region', 'interval_end'), name='uniq_region_interval')],
            },
        ),
        migrations.CreateModel(
            name='RegionWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('NSW1', 'NSW1'), ('QLD1', 'QLD1'), ('VIC1', 'VIC1'), ('SA1', 'SA1'), ('TAS1', 'TAS1')], max_length=8)),
                ('interval_end', models.DateTimeField(help_text='End of the 30-minute interval, NEM time (UTC+10).')),
                ('kind', models.CharField(choices=[('observed', 'Observed (reanalysis)'), ('forecast', 'Forecast (as issued ahead of time)')], max_length=10)),
                ('temperature_c', models.FloatField()),
            ],
            options={
                'ordering': ['region', 'interval_end'],
                'indexes': [models.Index(fields=['region', 'kind', 'interval_end'], name='nem_price_l_region_208a95_idx')],
                'constraints': [models.UniqueConstraint(fields=('region', 'interval_end', 'kind'), name='uniq_region_interval_kind')],
            },
        ),
        migrations.CreateModel(
            name='ForecastPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_end', models.DateTimeField()),
                ('predicted_rrp', models.FloatField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='nem_price_lab.forecastrun')),
            ],
            options={
                'ordering': ['interval_end'],
                'indexes': [models.Index(fields=['run', 'interval_end'], name='nem_price_l_run_id_35ded9_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'interval_end'), name='uniq_run_interval')],
            },
        ),
    ]
