# Generated by Django 5.2 on 2026-08-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nem_price_lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastrun',
            name='region',
            field=models.CharField(choices=[('NEM', 'NEM'), ('NSW1', 'NSW1'), ('QLD1', 'QLD1'), ('VIC1', 'VIC1'), ('SA1', 'SA1'), ('TAS1', 'TAS1')], max_length=8),
        ),
        migrations.AlterField(
            model_name='regionprice',
            name='region',
            field=models.CharField(choices=[('NEM', 'NEM'), ('NSW1', 'NSW1'), ('QLD1', 'QLD1'), ('VIC1', 'VIC1'), ('SA1', 'SA1'), ('TAS1', 'TAS1')], max_length=8),
        ),
        migrations.AlterField(
            model_name='regionweather',
            name='region',
            field=models.CharField(choices=[('NEM', 'NEM'), ('NSW1', 'NSW1'), ('QLD1', 'QLD1'), ('VIC1', 'VIC1'), ('SA1', 'SA1'), ('TAS1', 'TAS1')], max_length=8),
        ),
    ]
