# Generated by Django 5.2 on 2026-08-10 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basin',
            fields=[
                ('basin_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GasDataRefresh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sources', models.CharField(choices=[('reference', 'Reference: facilities, locations, connection points, capacity')], default='reference', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.TextField(blank=True, default='', help_text='Import summary (filled automatically).')),
            ],
            options={
                'verbose_name': 'gas data refresh',
                'verbose_name_plural': 'gas data refreshes',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='LinepackZone',
            fields=[
                ('code', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('operator', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('location_type', models.CharField(blank=True, max_length=20)),
                ('state', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True)),
                ('source_last_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['state', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('facility_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('short_name', models.CharField(blank=True, max_length=60)),
                ('facility_type', models.CharField(choices=[('BBGPG', 'Gas-powered generation'), ('BBLARGE', 'Large user'), ('BDIST', 'Blended distribution'), ('COMPRESSOR', 'Compression'), ('LNGEXPORT', 'LNG export'), ('PIPE', 'Pipeline'), ('PROD', 'Production'), ('STOR', 'Storage')], max_length=20)),
                ('type_description', models.CharField(blank=True, max_length=120)),
                ('operating_state', models.CharField(blank=True, max_length=20)),
                ('operating_state_date', models.DateField(blank=True, null=True)),
                ('operator_name', models.CharField(blank=True, max_length=160)),
                ('operator_id', models.IntegerField(blank=True, null=True)),
                ('source_last_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'facilities',
                'ordering': ['facility_type', 'name'],
                'indexes': [models.Index(fields=['facility_type'], name='gas_monitor_facilit_0f46fd_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConnectionPoint',
            fields=[
                ('connection_point_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('flow_direction', models.CharField(blank=True, choices=[('RECEIPT', 'Receipt'), ('DELIVERY', 'Delivery'), ('NONE', 'Not directional')], max_length=12)),
                ('node_id', models.IntegerField(blank=True, null=True)),
                ('state_name', models.CharField(blank=True, max_length=40)),
                ('demand_zone', models.CharField(blank=True, max_length=40)),
                ('source_last_updated', models.DateTimeField(blank=True, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_points', to='gas_monitor.facility')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connection_points', to='gas_monitor.location')),
            ],
            options={
                'ordering': ['facility', 'name'],
                'indexes': [models.Index(fields=['demand_zone'], name='gas_monitor_demand__80dcf7_idx')],
            },
        ),
        migrations.CreateModel(
            name='NameplateRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity_type', models.CharField(help_text='MDQ and similar AEMO capacity codes.', max_length=20)),
                ('flow_direction', models.CharField(blank=True, max_length=12)),
                ('receipt_location_id', models.IntegerField(blank=True, null=True)),
                ('receipt_location_name', models.CharField(blank=True, max_length=160)),
                ('delivery_location_id', models.IntegerField(blank=True, null=True)),
                ('delivery_location_name', models.CharField(blank=True, max_length=160)),
                ('capacity_tj', models.FloatField(help_text='Rated capacity in terajoules per day.')),
                ('effective_date', models.DateField()),
                ('capacity_description', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('source_last_updated', models.DateTimeField(blank=True, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nameplate_ratings', to='gas_monitor.facility')),
            ],
            options={
                'ordering': ['facility', '-effective_date'],
                'constraints': [models.UniqueConstraint(fields=('facility', 'capacity_type', 'receipt_location_id', 'delivery_location_id', 'effective_date'), name='uniq_nameplate_leg')],
            },
        ),
    ]
