# Generated by Django 5.2 on 2026-08-10 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32, unique=True)),
                ('last_run_at', models.DateTimeField()),
                ('earliest_gas_date', models.DateField(blank=True, null=True)),
                ('latest_gas_date', models.DateField(blank=True, null=True)),
                ('rows_stored', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'source coverage',
                'ordering': ['source'],
            },
        ),
        migrations.AlterField(
            model_name='gasdatarefresh',
            name='sources',
            field=models.CharField(choices=[('weekly', 'Weekly refresh: everything (the Monday ritual)'), ('time_series', 'Flows, forecasts, linepack flags, missing submissions'), ('reference', 'Reference: facilities, locations, connection points, capacity')], default='weekly', max_length=20),
        ),
        migrations.CreateModel(
            name='FlowForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas_date', models.DateField()),
                ('demand_tj', models.FloatField(default=0.0)),
                ('supply_tj', models.FloatField(default=0.0)),
                ('transfer_in_tj', models.FloatField(default=0.0)),
                ('transfer_out_tj', models.FloatField(default=0.0)),
                ('state', models.CharField(blank=True, max_length=10)),
                ('source_last_updated', models.DateTimeField(blank=True, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='gas_monitor.facility')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecasts', to='gas_monitor.location')),
            ],
            options={
                'ordering': ['gas_date', 'facility'],
                'indexes': [models.Index(fields=['gas_date'], name='gas_monitor_gas_dat_5b9a01_idx')],
                'constraints': [models.UniqueConstraint(fields=('gas_date', 'facility', 'location'), name='uniq_forecast_day_facility_location')],
            },
        ),
        migrations.CreateModel(
            name='FlowObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas_date', models.DateField(help_text='Gas day, starting 06:00 AEST.')),
                ('demand_tj', models.FloatField(default=0.0)),
                ('supply_tj', models.FloatField(default=0.0)),
                ('transfer_in_tj', models.FloatField(default=0.0)),
                ('transfer_out_tj', models.FloatField(default=0.0)),
                ('held_in_storage_tj', models.FloatField(blank=True, null=True)),
                ('cushion_gas_tj', models.FloatField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=10)),
                ('source_last_updated', models.DateTimeField(blank=True, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='gas_monitor.facility')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flows', to='gas_monitor.location')),
            ],
            options={
                'ordering': ['-gas_date', 'facility'],
                'indexes': [models.Index(fields=['-gas_date'], name='gas_monitor_gas_dat_78b2bc_idx'), models.Index(fields=['gas_date', 'state'], name='gas_monitor_gas_dat_6d7936_idx')],
                'constraints': [models.UniqueConstraint(fields=('gas_date', 'facility', 'location'), name='uniq_flow_day_facility_location')],
            },
        ),
        migrations.CreateModel(
            name='LinepackAdequacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas_date', models.DateField()),
                ('flag', models.CharField(choices=[('AMBER', 'Threatened'), ('GREEN', 'Adequate'), ('RED', 'Inadequate')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('source_last_updated', models.DateTimeField(blank=True, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linepack_flags', to='gas_monitor.facility')),
            ],
            options={
                'verbose_name_plural': 'linepack adequacy flags',
                'ordering': ['gas_date', 'facility'],
                'indexes': [models.Index(fields=['gas_date', 'flag'], name='gas_monitor_gas_dat_b5d656_idx')],
                'constraints': [models.UniqueConstraint(fields=('gas_date', 'facility'), name='uniq_lca_day_facility')],
            },
        ),
        migrations.CreateModel(
            name='MissingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas_date', models.DateField()),
                ('connection_point_id', models.IntegerField(default=-1)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_submissions', to='gas_monitor.facility')),
            ],
            options={
                'ordering': ['-gas_date', 'facility'],
                'constraints': [models.UniqueConstraint(fields=('gas_date', 'facility', 'connection_point_id'), name='uniq_missing_day_facility_point')],
            },
        ),
    ]
