# Generated by Django 5.2 on 2026-08-10

import decimal
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='BatteryAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('region', models.CharField(choices=[('NSW1', 'New South Wales'), ('QLD1', 'Queensland'), ('SA1', 'South Australia'), ('TAS1', 'Tasmania'), ('VIC1', 'Victoria')], max_length=4)),
                ('owner', models.CharField(blank=True, max_length=240)),
                ('custodian', models.CharField(blank=True, max_length=80)),
                ('aemo_survey_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('commitment_status', models.CharField(blank=True, max_length=40)),
                ('is_spike_cohort', models.BooleanField(default=False, help_text='Included in the initial three-asset, 30-day validation cohort.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'ordering': ['region', 'name']},
        ),
        migrations.CreateModel(
            name='BatteryRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duid', models.CharField(max_length=20)),
                ('direction_model', models.CharField(choices=[('bidirectional', 'Bidirectional unit'), ('generation', 'Legacy generation unit'), ('load', 'Legacy load unit')], default='bidirectional', max_length=20)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('power_capacity_mw', models.DecimalField(decimal_places=3, max_digits=10)),
                ('storage_capacity_mwh', models.DecimalField(decimal_places=3, max_digits=11)),
                ('aemo_generation_info_unit_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('unit_name', models.CharField(blank=True, max_length=160)),
                ('connection_point_id', models.CharField(blank=True, max_length=40)),
                ('source_name', models.CharField(max_length=120)),
                ('source_url', models.URLField(max_length=600)),
                ('source_published_on', models.DateField()),
                ('source_registry_version', models.CharField(max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='nem_battery_explorer.batteryasset')),
            ],
            options={
                'ordering': ['asset', 'effective_from', 'duid'],
                'indexes': [models.Index(fields=['duid', 'effective_from', 'effective_to'], name='nem_battery_duid_f600db_idx'), models.Index(fields=['asset', 'effective_from'], name='nem_battery_asset_i_6a4ff7_idx')],
                'constraints': [
                    models.UniqueConstraint(fields=('asset', 'duid', 'effective_from'), name='uniq_battery_registration_start'),
                    models.CheckConstraint(condition=models.Q(('power_capacity_mw__gt', decimal.Decimal('0'))), name='battery_power_capacity_positive'),
                    models.CheckConstraint(condition=models.Q(('storage_capacity_mwh__gt', decimal.Decimal('0'))), name='battery_storage_capacity_positive'),
                    models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='battery_registration_dates_ordered'),
                ],
            },
        ),
    ]
