# Generated by Django 5.2 on 2026-08-10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('nem_battery_explorer', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='BatteryDataRefresh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('requested_start', models.DateField()),
                ('requested_end', models.DateField()),
                ('completed_through', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('complete', 'Complete'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=12)),
                ('calculation_version', models.CharField(default='mvp-v1', max_length=30)),
                ('source_receipts', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True)),
            ],
            options={'ordering': ['-started_at']},
        ),
        migrations.CreateModel(
            name='RegionPriceInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_date', models.DateField()),
                ('region', models.CharField(choices=[('NSW1', 'New South Wales'), ('QLD1', 'Queensland'), ('SA1', 'South Australia'), ('TAS1', 'Tasmania'), ('VIC1', 'Victoria')], max_length=4)),
                ('interval_end', models.DateTimeField(help_text='Interval end stored as fixed NEM time (UTC+10).')),
                ('rrp', models.FloatField(help_text='Regional reference price in $/MWh.')),
                ('fcas_prices', models.JSONField(default=dict)),
                ('source_file', models.CharField(max_length=180)),
            ],
            options={
                'ordering': ['region', 'interval_end'],
                'indexes': [models.Index(fields=['operating_date', 'region'], name='nem_battery_operati_66297e_idx')],
                'constraints': [models.UniqueConstraint(fields=('region', 'interval_end'), name='uniq_battery_region_price_interval')],
            },
        ),
        migrations.CreateModel(
            name='BatteryDispatchInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_date', models.DateField()),
                ('interval_end', models.DateTimeField(help_text='Interval end stored as fixed NEM time (UTC+10).')),
                ('initial_mw', models.FloatField(blank=True, null=True)),
                ('dispatch_target_mw', models.FloatField(blank=True, null=True)),
                ('scada_mw', models.FloatField(blank=True, null=True)),
                ('availability_mw', models.FloatField(blank=True, null=True)),
                ('initial_energy_storage_mwh', models.FloatField(blank=True, null=True)),
                ('energy_storage_mwh', models.FloatField(blank=True, null=True)),
                ('fcas_enablement_mw', models.JSONField(default=dict)),
                ('charge_mwh', models.FloatField(default=0.0)),
                ('discharge_mwh', models.FloatField(default=0.0)),
                ('charging_cost', models.FloatField(default=0.0)),
                ('discharge_value', models.FloatField(default=0.0)),
                ('energy_market_value', models.FloatField(default=0.0)),
                ('gross_fcas_value', models.FloatField(default=0.0)),
                ('observable_gross_value', models.FloatField(default=0.0)),
                ('quality_flags', models.JSONField(blank=True, default=list)),
                ('dispatch_source_file', models.CharField(max_length=180)),
                ('scada_source_file', models.CharField(max_length=180)),
                ('regional_price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='battery_intervals', to='nem_battery_explorer.regionpriceinterval')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intervals', to='nem_battery_explorer.batteryregistration')),
            ],
            options={
                'ordering': ['registration', 'interval_end'],
                'indexes': [models.Index(fields=['operating_date', 'registration'], name='nem_battery_operati_a95a42_idx'), models.Index(fields=['registration', 'interval_end'], name='nem_battery_registr_40a7c4_idx')],
                'constraints': [models.UniqueConstraint(fields=('registration', 'interval_end'), name='uniq_battery_dispatch_interval')],
            },
        ),
        migrations.CreateModel(
            name='BatteryDailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_date', models.DateField()),
                ('interval_count', models.PositiveSmallIntegerField(default=0)),
                ('scada_interval_count', models.PositiveSmallIntegerField(default=0)),
                ('storage_interval_count', models.PositiveSmallIntegerField(default=0)),
                ('charge_mwh', models.FloatField(default=0.0)),
                ('discharge_mwh', models.FloatField(default=0.0)),
                ('throughput_mwh', models.FloatField(default=0.0)),
                ('equivalent_cycles', models.FloatField(default=0.0)),
                ('charging_cost', models.FloatField(default=0.0)),
                ('discharge_value', models.FloatField(default=0.0)),
                ('energy_market_value', models.FloatField(default=0.0)),
                ('gross_fcas_value', models.FloatField(default=0.0)),
                ('observable_gross_value', models.FloatField(default=0.0)),
                ('value_per_discharge_mwh', models.FloatField(blank=True, null=True)),
                ('capture_price', models.FloatField(blank=True, null=True)),
                ('peak_charge_mw', models.FloatField(default=0.0)),
                ('peak_discharge_mw', models.FloatField(default=0.0)),
                ('min_storage_mwh', models.FloatField(blank=True, null=True)),
                ('max_storage_mwh', models.FloatField(blank=True, null=True)),
                ('min_state_of_charge_pct', models.FloatField(blank=True, null=True)),
                ('max_state_of_charge_pct', models.FloatField(blank=True, null=True)),
                ('top_five_interval_value_share', models.FloatField(blank=True, null=True)),
                ('quality_status', models.CharField(choices=[('complete', 'Complete'), ('partial', 'Partial')], default='partial', max_length=12)),
                ('quality_notes', models.JSONField(blank=True, default=list)),
                ('calculation_version', models.CharField(default='mvp-v1', max_length=30)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='nem_battery_explorer.batteryasset')),
            ],
            options={
                'ordering': ['-operating_date', 'asset'],
                'indexes': [models.Index(fields=['operating_date', 'quality_status'], name='nem_battery_operati_295061_idx')],
                'constraints': [models.UniqueConstraint(fields=('asset', 'operating_date'), name='uniq_battery_daily_summary')],
            },
        ),
    ]
