# Generated by Django 5.2 on 2025-06-10 11:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_blogpost_external_url_blogpost_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='published',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
