# Generated by Django 5.2 on 2026-06-24

from django.db import migrations, models


def publish_existing_posts(apps, schema_editor):
    BlogPost = apps.get_model('portfolio', 'BlogPost')
    BlogPost.objects.filter(published__isnull=False).update(status='published')


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(
                choices=[
                    ('energy', 'Energy transition'),
                    ('data', 'Data & methods'),
                    ('society', 'Society & policy'),
                    ('sport', 'Sport & performance'),
                    ('other', 'Other'),
                ],
                default='other',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='key_takeaway',
            field=models.TextField(blank=True, help_text='Optional one-sentence insight shown prominently on the article page.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='status',
            field=models.CharField(
                choices=[('draft', 'Draft'), ('published', 'Published')],
                default='draft',
                max_length=20,
            ),
        ),
        migrations.RunPython(publish_existing_posts, migrations.RunPython.noop),
    ]
