# Generated by Django 5.2 on 2026-06-24

from django.db import migrations


def refine_existing_article_metadata(apps, schema_editor):
    BlogPost = apps.get_model('portfolio', 'BlogPost')

    BlogPost.objects.filter(slug='climate-change-part-4').update(
        category='energy',
        key_takeaway=(
            "Country clusters reveal that fair climate policy should respond to each "
            "economy's emission profile, not just its total emissions."
        ),
    )
    BlogPost.objects.filter(slug='parkrun-performance-analysis').update(
        category='sport',
        key_takeaway=(
            'Personal performance analysis can turn a running log into a realistic, '
            'data-led training target.'
        ),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_blogpost_editorial_fields'),
    ]

    operations = [
        migrations.RunPython(refine_existing_article_metadata, migrations.RunPython.noop),
    ]
