# Generated by Django 5.2 on 2026-06-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_blogpost_updated_at_alter_blogpost_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('energy', 'Energy transition'), ('data', 'Data & methods'), ('society', 'Society & policy'), ('sport', 'Human performance')], default='energy', max_length=20),
        ),
    ]
