# Generated by Django 5.2 on 2026-06-25 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_blogpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('energy', 'Energy transition'), ('data', 'Data Stories'), ('society', 'Society & policy'), ('sport', 'Human performance')], default='energy', max_length=20),
        ),
    ]
