# Generated by Django 5.2 on 2026-07-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('energy', 'Energy Systems'), ('data', 'Data Stories'), ('sport', 'Human Performance'), ('commercial', 'Commercial Intelligence')], default='energy', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('energy', 'Energy Systems'), ('data', 'Data Stories'), ('sport', 'Human Performance'), ('commercial', 'Commercial Intelligence')], default='energy', max_length=20),
        ),
    ]
