# Generated by Django 5.2 on 2026-08-20 05:04
#
# Despite the "0005" filename, this is deliberately positioned to run
# BEFORE 0003_migrate_blob_data (see its dependencies, hand-edited below,
# and 0003's dependencies, also hand-edited to point here instead of
# 0002) — production has real data with values longer than the original
# 300-char CharField limits, which made 0003 fail with
# StringDataRightTruncation partway through the blob migration. Widening
# these columns needs to happen before 0003 runs, not after.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life_compass', '0002_calendarmark_historicalcalendarmark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytask',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='doneledgerentry',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='historicalkanbancard',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicalstrategy',
            name='current_season',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicalstrategy',
            name='north_star',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicalstrategy',
            name='principle',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicalstrategy',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicalweeklyfocus',
            name='health',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicalweeklyfocus',
            name='main',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicalweeklyfocus',
            name='secondary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='kanbancard',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='current_season',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='north_star',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='principle',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='weeklyfocus',
            name='health',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='weeklyfocus',
            name='main',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='weeklyfocus',
            name='secondary',
            field=models.TextField(blank=True),
        ),
    ]
