# Generated by Django 5.2 on 2026-06-26 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stillpoint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidedmeditation',
            name='audio',
            field=models.FileField(help_text='MP3 only.', upload_to='stillpoint/', validators=[django.core.validators.FileExtensionValidator(['mp3'])]),
        ),
    ]
