# Generated by Django 5.2 on 2026-08-19 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stillpoint', '0002_alter_guidedmeditation_audio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StillpointSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField()),
                ('duration_seconds', models.PositiveIntegerField()),
                ('mode', models.CharField(choices=[('master', 'Master'), ('student', 'Guide me')], default='master', max_length=16)),
                ('guided_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='stillpoint.guidedmeditation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stillpoint_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
